/**
 * Single source of truth for the Material Symbols glyphs bundled into the app.
 *
 * These names drive the self-hosted subset generated by
 * `scripts/generate-material-symbols-font.ts` (npm run `generate:material-symbols-font`),
 * which writes `src/assets/icons/material-symbols-outlined.woff2` + the generated
 * `src/styles/_material-symbols.scss` @font-face partial.
 *
 * After adding/removing an icon here you MUST regenerate the font, otherwise the
 * new glyph renders as tofu (missing) and removed glyphs keep bloating the woff2.
 *
 * No need to keep this sorted -> the generator sorts + de-dupes before subsetting.
 */
export const MATERIAL_SYMBOLS_ICON_NAMES: readonly string[] = [
  'bar_chart',
  'calculate',
  'check_circle',
  'clear',
  'compare_arrows',
  'delete',
  'edit',
  'error',
  'help',
  'keyboard_double_arrow_left',
  'keyboard_double_arrow_right',
  'menu',
  'payments',
  'person_add',
  'list_alt',
  'share',
];
