version: 2.1
orbs:
  node: circleci/node@5
jobs:
  build:
    executor: node/default
    working_directory: ~/my-earnings-today
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          command: npm run build:production
      - persist_to_workspace:
            root: ~/my-earnings-today
            paths:
                - .
  deploy:
    working_directory: ~/my-earnings-today
    docker:
      - image: cimg/base:2024.02
    steps:
      - attach_workspace:
            at: ~/my-earnings-today
      - add_ssh_keys:
          fingerprints:
            - "SHA256:URTfidP7xVnBRdhWO03zsI0UdDd1nk+ht5pqT1f4UcY"
      - run:
          command: |
            mkdir -p ~/.ssh
            ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts
            scp -rv ./dist/my-earnings-today/* $SSH_USER@$SSH_HOST:apps/my-earnings-today
workflows:
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
